---
title: "tidyYarns Exploratory Data Analysis"
---
#Load library and data dependencies
```{r}
library(ggplot2)
source("tidyYarns.R")

pur_df <- read.csv("~/Washougal-Mill-Study/CSVs/Stops-PurchasedYarns.csv",
                           stringsAsFactors=FALSE)
twist_df <-read.csv("~/Washougal-Mill-Study/CSVs/Stops-TwistYarns.csv",
                            stringsAsFactors=FALSE)
dyed_df <-read.csv("~/Washougal-Mill-Study/CSVs/Stops-DyedYarns.csv",
                           stringsAsFactors=FALSE)
spun_df <- read.csv("~/Washougal-Mill-Study/CSVs/Stops-SpunYarns.csv",
                            stringsAsFactors=FALSE)

raw_yarns <- bind_rows(pur_df, twist_df, dyed_df, spun_df)

tidy_yarns <- tidyYarns()
```

# head of tidy_yarns
```{r}
head(tidy_yarns, 10)
```



# Total number of yarns
```{r}
length(unique(tidy_yarns$yarn))
```

# Yarn type distribution
```{r}
ggplot(data = tidy_yarns) +
        geom_bar(mapping = aes(type))
```

# Unique Dyed Yarns
```{r}
dye <- unique(tidy_yarns[which(tidy_yarns$type == "Dye"),])
length(dye$yarn)

```



# Unique Purchased Yarns
```{r}
pur <- unique(tidy_yarns[which(tidy_yarns$type == "Pur"),])
length(pur$yarn)
```

# Unique Spun Yarns

```{r}
spun <- unique(tidy_yarns[which(tidy_yarns$type == "Spun"),])
length(spun$yarn)
```

# Unique Twist Yarns

```{r}
twist <- unique(tidy_yarns[which(tidy_yarns$type == "Twist"),])
length(twist$yarn)
```

