---
title: "tidyStopsEDA"
---

```{r}
library(ggplot2)
library(dplyr)
source("tidyStops.R")

raw_stops <- read.csv("~/Washougal-Mill-Study/CSVs/Stops-Extract.csv",
                           stringsAsFactors=FALSE)
tidy_stops <- tidyStops()
```


# dimensions of data
```{r}
dim(tidy_stops)
```

# head of data
```{r}
head(tidy_stops, 10)
```

# range of dates
```{r}
stops_range <-range(tidy_stops$date)
stops_range
```

# weeks of data
```{r}
difftime(stops_range[1], stops_range[2], units="weeks")
```

# days of data
```{r}
difftime(stops_range[1], stops_range[2])
```


# loom utilization distribution
```{r}
qplot(tidy_stops$loom)
```

# Shift Distribution
```{r}
qplot(tidy_stops$shift)
```

# Stops Distribution by Stop Type
```{r}
stop_counts <- tidy_stops %>% 
        summarise(totalweft = sum(weft, na.rm=T),
                  totalwarp = sum(warp, na.rm=T), 
                  totalother = sum(other, na.rm=T))
stop_counts
```


# Summary

```{r}
summary(tidy_stops[,-1:-9])
```

```{r}
range(tidy_stops$ppm)
```

```{r}
unique(tidy_stops$ppm)
```



```{r}
filtered_stops <- tidy_stops %>% filter(ppm > 50 & hoursweaving < 10)
```


# Shift Separation

```{r}
shift1_stops <- tidy_stops[which(tidy_stops$shift == 1),]
shift2_stops <- tidy_stops[which(tidy_stops$shift == 2),]
shift3_stops <- tidy_stops[which(tidy_stops$shift == 3),]
```

## Shift 1
```{r}
summary(shift1_stops[,-1:-9])
```

## Shift 2
```{r}
summary(shift2_stops[,-1:-9])
```

## Shift 3
```{r}
summary(shift3_stops[,-1:-9])
```





# Loom Seperation
```{r}
for(i in 1:30){
        paste("shift",i,"_stops", sep="") <- tidy_stops[which(tidy_stops$loom == i),]
}
```

